apiVersion: v1
kind: Service
metadata:
  name: cdn-controlplane
  labels:
    app.kubernetes.io/name: cdn-controlplane
    app.kubernetes.io/component: controlplane
    app.kubernetes.io/part-of: cdn
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cdn-controlplane
    app.kubernetes.io/component: controlplane
  ports:
    - name: http
      port: 9090
      targetPort: http
      protocol: TCP
